language: python

branches:
  only:
    - master

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem 1.6.2
  - sudo luarocks install busted 1.11.1
  - sudo luarocks install luasocket

services:
  - redis

script: "make install_dev; make test"

notifications:
  recipients:
    - jbochi@gmail.com
  email:
    on_success: change
    on_failure: always
